name: Test Playground

on:
  push:
    branches: [ gh-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.0', '8.0']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start mysql
      run: |
        (echo '[mysqld]'; echo 'default-authentication-plugin=mysql_native_password') | sudo sh -c "cat > /etc/mysql/conf.d/nativepassword.cnf"
        sudo systemctl start mysql
        mysql -V

    - name: Prepare the application
      run: |
        sudo lib/createdb.sh -u root -proot -c test/options.php --batch
        sudo lib/createdb.sh -u root -proot -c test/cdb-options.php --no-dbuser --batch

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, mysqlnd

    - name: Install poppler
      run: |
        sudo apt-get --fix-broken install
        sudo apt-get install poppler-utils

    - name: Run tests
      run: sh test/check.sh
